#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────
# build-clients.sh
#
# Builds the Fyne GUI client for available platforms.
# macOS (.app) is built natively.
# Windows (.exe) and Linux require MinGW/Cross-compilers if built from macOS.
# ──────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CLIENT_DIR="${PROJECT_ROOT}/client"
BIN_DIR="${PROJECT_ROOT}/bin"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   🖥️  Building Computer Control (GUI)        ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════╝${NC}"
echo ""

# Ensure fyne CLI is installed
if ! command -v fyne &> /dev/null; then
    echo -e "${YELLOW}⚠️ fyne CLI not found. Installing it now...${NC}"
    go install fyne.io/tools/cmd/fyne@latest
    # Ensure it's in the PATH
    export PATH=$PATH:$(go env GOPATH)/bin
fi

# Clean and create bin directory
rm -rf "${BIN_DIR}"
mkdir -p "${BIN_DIR}"

# Navigate to client directory so go.mod and icon.png are found
cd "${CLIENT_DIR}"

# Embed version from package.json for auto-update version check
VERSION=$(node -p "require('${PROJECT_ROOT}/package.json').version")
printf 'package main\n\n// clientVersion is set at build time from package.json\nvar clientVersion = "%s"\n' "${VERSION}" > version.go

# ──────────────────────────────────────────────
# Build target: macOS (.app)
# ──────────────────────────────────────────────
echo -e "  ${YELLOW}⏳ Building macOS (.app bundle)...${NC}"
# Fyne package will read FyneApp.toml and package it nicely
fyne package -os darwin --app-id com.homebridge.computer-control

if [ -d "Computer Control.app" ]; then
    echo -e "  ${YELLOW}🔧 Making app invisible in Dock (LSUIElement)...${NC}"
    # Insert the LSUIElement key into the Info.plist generated by fyne
    /usr/bin/plutil -insert LSUIElement -bool true "Computer Control.app/Contents/Info.plist"

    # Rename and move to /bin
    mv "Computer Control.app" "${BIN_DIR}/ComputerControl.app"
    # Zip for download (macOS Finder: double-click to extract; Gatekeeper: right-click → Open or xattr -cr)
    (cd "${BIN_DIR}" && zip -r -q computer-control-darwin-app.zip ComputerControl.app)
    echo -e "  ${GREEN}✅ macOS -> bin/ComputerControl.app (+ .zip)${NC}"
else
    echo -e "  ${RED}❌ macOS build failed.${NC}"
fi

# ──────────────────────────────────────────────
# Build target: Windows (.exe)
# ──────────────────────────────────────────────
echo -e "  ${YELLOW}⏳ Building Windows (.exe)...${NC}"
# For macOS to compile Windows CGO, x86_64-w64-mingw32-gcc is needed.
if command -v x86_64-w64-mingw32-gcc &> /dev/null; then
    CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=amd64 fyne package -os windows --app-id com.homebridge.computer-control
    if [ -f "Computer Control.exe" ]; then
        mv "Computer Control.exe" "${BIN_DIR}/computer-control-windows-amd64.exe"
        echo -e "  ${GREEN}✅ Windows -> bin/computer-control-windows-amd64.exe${NC}"
    else
        echo -e "  ${RED}❌ Windows build failed.${NC}"
    fi
else
    echo -e "  ${RED}⚠️  Skipping Windows build!${NC}"
    echo -e "     Cross-compiling Windows GUI from macOS requires MinGW."
    echo -e "     Install it via: ${CYAN}brew install mingw-w64${NC}"
fi

# ──────────────────────────────────────────────
# Build target: Linux
# ──────────────────────────────────────────────
echo -e "  ${YELLOW}⏳ Building Linux binary...${NC}"
if command -v x86_64-linux-musl-gcc &> /dev/null || command -v x86_64-pc-linux-gnu-gcc &> /dev/null; then
    # Very basic attempt at linux cross compile. Usually fyne-cross is better for this.
    CGO_ENABLED=1 GOOS=linux GOARCH=amd64 fyne package -os linux --app-id com.homebridge.computer-control || echo -e "  ${RED}⚠️ Linux compilation requires docker based fyne-cross usually on macOS.${NC}"
    if [ -f "Computer Control.tar.xz" ]; then
        mv "Computer Control.tar.xz" "${BIN_DIR}/computer-control-linux-amd64.tar.xz"
        echo -e "  ${GREEN}✅ Linux -> bin/computer-control-linux-amd64.tar.xz${NC}"
    elif [ -f "Computer Control" ]; then
        mv "Computer Control" "${BIN_DIR}/computer-control-linux-amd64"
        echo -e "  ${GREEN}✅ Linux -> bin/computer-control-linux-amd64${NC}"
    fi
else
    echo -e "  ${RED}⚠️  Skipping Linux build!${NC}"
    echo -e "     Cross-compiling Linux GUI from macOS requires Linux GCC or fyne-cross (Docker)."
    echo -e "     For Linux, it's easiest to build directly on the Linux machine."
fi

# Return to root
cd "${PROJECT_ROOT}"

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   📋 Build Summary                           ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════╝${NC}"
echo ""
ls -lh "${BIN_DIR}/" || echo "No binaries generated."
echo ""
echo -e "${GREEN}🎉 Build process complete!${NC}"
